[APP]
base_url=https://company.com

[BROWSER]
browser=chrome
headless=False
timeout=30

[CREDENTIALS]
username=prod_user
password=prod_password

[GRID]

;execution=grid
execution=local
grid_url=http://selenium-hub:4444
platform=WINDOWS
browser_version=latest