[APP]
base_url=https://www.saucedemo.com

[BROWSER]
browser=chrome
headless=False
timeout=10

[CREDENTIALS]
username=standard_user
password=secret_sauce

[GRID]

execution=grid
;execution=local
grid_url=http://selenium-hub:4444
platform=WINDOWS
browser_version=latest