[APP]
base_url=https://stage.company.com

[BROWSER]
browser=chrome
headless=True
timeout=20

[CREDENTIALS]
username=stage_user
password=stage_password

[GRID]
;execution=grid
execution=local
grid_url=http://selenium-hub:4444
platform=WINDOWS
browser_version=latest